service user
ssnk-test/stage_proj pull request #10
Opened 2020-08-04 22:39 UTC by ssnk-test

2020-08-05 00:23 UTC, s3rius commented on user_service/alembic/versions/3437ddf66dba_.py
> +    pass
Пустые миграции удаляй.

2020-08-05 00:24 UTC, s3rius commented on user_service/alembic/versions/7ea9ab281b59_.py
> +    pass
Опять пустая.

2020-08-05 00:24 UTC, s3rius commented on user_service/alembic/versions/adf72d2b2966_.py
> +    pass
Опять пустая.

2020-08-05 00:25 UTC, s3rius commented on user_service/app/model.py
> +users = Table(
Лучше попробуй через declarativeBase, чем Table.

2020-08-05 00:26 UTC, s3rius commented on user_service/app/model.py
> +    Column("email", String(20), nullable=True, unique=True),
Думаю, что маловато.
У меня была почта "pavelentiy@le-memese.com" (24 символа). У знакомого и того больше. Так что 120 поставь.

2020-08-05 00:27 UTC, s3rius commented on user_service/app/routes.py
> +    app.router.add_view("/registr", RegView)
Очепятка в урле.

Правильно: register.

2020-08-05 00:28 UTC, s3rius commented on user_service/app/views.py
> +# import aiohttp_jinja2
Коменты удаляй такие.

2020-08-05 00:35 UTC, s3rius commented on user_service/app/views.py
> +def auth(f):
Тут немного неверная логика работы. Прикол в том, что в идеале токен должен передаваться через хедеры, чтобы не мешать передачи чистой информации. Обычно используют `Bearer` токены, которые помещены в хедер `Authorization`. Вот пример хедера:
```json
{
   "Authorization": "Bearer <actual_token>"
}
```

2020-08-05 00:36 UTC, s3rius commented on user_service/app/views.py
> +                    "todo:implement to env")
От тудушечек почистить.

2020-08-05 00:36 UTC, s3rius commented on user_service/app/views.py
> +                        "exp": datetime.now()
Ошибочка. exp должен быть на 15\40 минут позже. В зависимости от типа токена.

2020-08-05 00:37 UTC, s3rius commented on user_service/app/views.py
> +                a_tocken = jwt.encode(
Очепятка.
`a_token`.

2020-08-05 00:40 UTC, s3rius commented on user_service/app/views.py
> +        r_tok =  await redis.get(body_dict["atoken"])
У тебя странная структура у редиса. Типа, ты делаешь 2 запроса, а надо 1. Подумай, как уменьшить кол-во запросов и хранимой информации. (С одной сессии юзера у тебя должна должна асоциироваться 1 запись).

2020-08-05 00:43 UTC, s3rius commented on user_service/app/views.py
> +            data_dict[0] = body_dict["user"]
Ты можешь сделать проще. 
Типа, pop всех нежелательных параметров (кроме пароля), а потом заполнить data_dict с нужными ключами и выполнить подобного рода операцию.
```python

        async with self.request.app["database_pool"].acquire() as conn:
            query = users.update().values(**data_dict)
            await conn.execute(query)
```

2020-08-05 00:43 UTC, s3rius commented on user_service/app/views.py
> +            data_dict[0] = body_dict["user"]
Читается проще и писать быстрее.

2020-08-05 00:44 UTC, s3rius commented on user_service/app/views.py
> +    async def post(self):
Инфо через post это как-то не по REST. Переведи токены на хедеры, тогда тебе не надо будет явно передавать его и можно будет перевести на GET, как и подобает.

2020-08-05 00:45 UTC, s3rius commented on user_service/app/views.py
> +                "exp": datetime.now()
Опять время неверное.

2020-08-05 00:45 UTC, s3rius commented on user_service/app/views.py
> +                "exp": datetime.now()
Так на клиенте нельзя будет определить когда токен протухнет и понять, надо ли обновлять или нет.

2020-08-05 00:47 UTC, s3rius commented on user_service/main.py
> +# from aiohttp_security import SessionIdentityPolicy
Опять же коменты.

![image](https://user-images.githubusercontent.com/18153319/89359356-b074a000-d6d6-11ea-92f5-d26482694fdc.png)

2020-08-05 00:47 UTC, s3rius commented on user_service/main.py
> +
Чото пробелов много и коменты.

2020-08-05 00:47 UTC, s3rius commented on user_service/main.py
> +
Очень много коментов. 
Также не забывай про black.

2020-08-05 00:49 UTC, s3rius commented on user_service/main.py
> +    parser.add_argument("-c", "--config", help="Provide path to config file")
Грузи из environ. А для подгрузки параметров юзай pydantic.

Вот примерчик годного конфига:
https://gitlab.le-memese.com/telegram-bots/bot_s3rius/-/blob/master/src/config.py

2020-08-19 16:09 UTC, ssnk-test commented on user_service/alembic/versions/3437ddf66dba_.py
> +    pass
исправил https://github.com/ssnk-test/stage_proj/pull/10/commits/861b5439d767748e94dc7b66c111a3f83e9a13e5

2020-08-19 16:09 UTC, ssnk-test commented on user_service/alembic/versions/7ea9ab281b59_.py
> +    pass
исправил https://github.com/ssnk-test/stage_proj/pull/10/commits/861b5439d767748e94dc7b66c111a3f83e9a13e5

2020-08-19 16:18 UTC, ssnk-test commented on user_service/alembic/versions/adf72d2b2966_.py
> +    pass
исправил https://github.com/ssnk-test/stage_proj/pull/10/commits/861b5439d767748e94dc7b66c111a3f83e9a13e5

2020-08-20 01:01 UTC, ssnk-test commented on user_service/app/model.py
> +users = Table(
Исправил https://github.com/ssnk-test/stage_proj/commit/483da439b6a6e6686d2a3945efab296b156c2fe8

2020-08-20 01:02 UTC, ssnk-test commented on user_service/app/model.py
> +    Column("email", String(20), nullable=True, unique=True),
исправил https://github.com/ssnk-test/stage_proj/commit/483da439b6a6e6686d2a3945efab296b156c2fe8

2020-08-23 23:35 UTC, s3rius requested changes
Уже намного приятнее. Давай последний рывок.

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +        if "Bearer" in header_auth:
Мб `startswith`?

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +            return web.json_response({"response": "no valid atoken"})
```suggestion
            return web.json_response({"response": "invalid auth token"})
```

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +            return web.json_response({"response": "no valid atoken"})
```suggestion
            return web.json_response({"response": "invalid auth token"})
```

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +            if user is not None:
Лучше делать блоки with с acquire() как можно меньше и вызывать их только для выполнения запроса. Потому что так ты держишь коннект открытым, чего тебе в целом-то и не надо. Плюс тут у тебя хеширование аргоном, который сам по себе довольно жирный.

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +                return web.json_response({"atoken": a_token, "rtoken": r_token})
```suggestion
        async with self.request.app["database_pool"].acquire() as conn:
            user = await conn.fetchrow(
                sa.select([Users]).where(Users.username == body_dict['username']))

        if user is not None:
            pass_crypt = user["password"]
            ph = argon.PasswordHasher()

            try:
                ph.verify(pass_crypt, body_dict["password"])
            except argon.exceptions.VerifyMismatchError:
                return web.json_response({"resp": "wrong password"})

            a_token = jwt.encode(
                {
                    "username": body_dict['username'],
                    "exp": datetime.now() + timedelta(minutes=15),
                    "uuid": user["uuid"]
                },
                settings.jwt_phrase)
            r_token = jwt.encode(
                {
                    "username": body_dict['username'],
                    "exp": datetime.now() + timedelta(minutes=40),
                    "uuid": user["uuid"]
                },
                settings.jwt_phrase)

            redis = self.request.app["redis_pool"]
            await redis.set(user["uuid"], " ".join([a_token, r_token]))
            await redis.expire(user["uuid"], 60 * 40)

            return web.json_response({"atoken": a_token, "rtoken": r_token})

```

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +            await conn.fetchrow(query)
Если сработает такой вариант, то лучше так. Это не пересылает лишние байтики обратно по сети.
```suggestion
            await conn.execute(query)
```

2020-08-23 23:35 UTC, s3rius commented on user_service/app/views.py
> +            return web.json_response({"response": "no rtoken"})
```suggestion
            return web.json_response({"response": "no refresh token"})
```

2020-08-23 23:35 UTC, s3rius commented on user_service/config/config.py
> +class Settings(BaseSettings):
:heart: Удобнее же стало?

2020-08-24 00:33 UTC, ssnk-test commented on user_service/app/views.py
> +        if "Bearer" in header_auth:
исправил
https://github.com/ssnk-test/stage_proj/pull/10/commits/d45b360e97ba8c8fef0b0c0b0aa38090770c1551

2020-08-24 00:34 UTC, ssnk-test commented on user_service/app/views.py
> +            await conn.fetchrow(query)
работает
https://github.com/ssnk-test/stage_proj/pull/10/commits/d45b360e97ba8c8fef0b0c0b0aa38090770c1551

2020-08-24 00:37 UTC, ssnk-test commented on user_service/config/config.py
> +class Settings(BaseSettings):
ага)

2020-08-24 00:47 UTC, ssnk-test commented on user_service/app/views.py
> +            return web.json_response({"response": "no valid atoken"})
fix 
https://github.com/ssnk-test/stage_proj/pull/10/commits/7936613672af641add90300f9aa3c78858b28a95

2020-08-24 00:47 UTC, ssnk-test commented on user_service/app/views.py
> +            return web.json_response({"response": "no valid atoken"})
fix 
https://github.com/ssnk-test/stage_proj/pull/10/commits/7936613672af641add90300f9aa3c78858b28a95

2020-08-24 00:48 UTC, ssnk-test commented on user_service/app/views.py
> +            return web.json_response({"response": "no rtoken"})
fix 
https://github.com/ssnk-test/stage_proj/pull/10/commits/7936613672af641add90300f9aa3c78858b28a95

2020-08-24 00:52 UTC, ssnk-test commented on user_service/app/views.py
> +            if user is not None:
Понятно

2020-08-24 00:54 UTC, ssnk-test commented on user_service/app/views.py
> +                return web.json_response({"atoken": a_token, "rtoken": r_token})
пофикшено
https://github.com/ssnk-test/stage_proj/pull/10/commits/3b96607f091cc07fec5cbb91a0ba6c1504539258

2020-08-24 09:42 UTC, s3rius requested changes
Немного не поправлено.

2020-08-24 09:42 UTC, s3rius commented on user_service/app/views.py
> +            if user is not None:
Надо исправить. У тебя всё ещё много логики внутри acquire.

2020-08-24 09:43 UTC, s3rius approved these changes

2020-08-24 09:43 UTC, merged