Add email service
ssnk-test/stage_proj pull request #11
Opened 2020-08-13 20:45 UTC by ssnk-test

#goods3

2020-08-18 00:13 UTC, s3rius commented on user_service/alembic/env.py
> +sys.path = sys.path[:] + [".."]
Лучше разобраться с модулями, чем менять PATH.

2020-08-18 00:13 UTC, s3rius commented on user_service/alembic/env.py
> +sys.path = sys.path[:] + [".."]
Но как решение тоже ок.

2020-08-18 00:14 UTC, s3rius commented on user_service/alembic/versions/7ea9ab281b59_.py
> +def upgrade():
Пустые миграции можно удалить.

2020-08-18 00:14 UTC, s3rius commented on user_service/alembic/versions/adf72d2b2966_.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Пустышка.

2020-08-18 00:14 UTC, s3rius commented on user_service/alembic/versions/3437ddf66dba_.py
> +    pass
Пусто, можно удолять.

2020-08-18 00:16 UTC, s3rius commented on user_service/app/views.py
> +            if not await redis.exists(body_dict["atoken"]):
Лучше передавать в `Authorization` хедере и брать оттуда же. Чтобы данные не аффектить.

2020-08-18 00:17 UTC, s3rius commented on user_service/app/views.py
> +                    "todo:implement to env")
Самое время.

2020-08-18 00:17 UTC, s3rius commented on user_service/app/views.py
> +        print("LogOut valid auth")
Принты удалить. Только через logging позволительно.

2020-08-18 00:19 UTC, s3rius commented on email_service/src/email_service/views/templates.py
> +from ..models.templates import Templates
Нельзя использовать rel импорты. Указывай полный путь.

2020-08-18 00:19 UTC, s3rius commented on mon/app_mon/models/__init__.py
> +    dsn="postgresql://postgres:postgres@db_mon_service:5432/postgres",
Вынеси в Env.

2020-08-18 00:20 UTC, s3rius commented on mon/app_mon/views/events.py
> +from ...cel.tasks import write_event
Опять rel импорты.

2020-08-23 17:04 UTC, ssnk-test commented on user_service/alembic/versions/7ea9ab281b59_.py
> +def upgrade():
исправлено в предыдущем сервисе
https://github.com/ssnk-test/stage_proj/pull/10/commits/483da439b6a6e6686d2a3945efab296b156c2fe8

2020-08-23 17:04 UTC, ssnk-test commented on user_service/alembic/versions/adf72d2b2966_.py
> +    # ### commands auto generated by Alembic - please adjust! ###
исправлено в предыдущем сервисе
https://github.com/ssnk-test/stage_proj/pull/10/commits/483da439b6a6e6686d2a3945efab296b156c2fe8

2020-08-23 17:04 UTC, ssnk-test commented on user_service/alembic/versions/3437ddf66dba_.py
> +    pass
исправлено в предыдущем сервисе
https://github.com/ssnk-test/stage_proj/pull/10/commits/483da439b6a6e6686d2a3945efab296b156c2fe8

2020-08-23 17:08 UTC, ssnk-test commented on user_service/app/views.py
> +            if not await redis.exists(body_dict["atoken"]):
переделано в предыдущем сервисе
вот тут https://github.com/ssnk-test/stage_proj/pull/10/commits/eaec194810fde7f1bc9315be5c6c86ec55250157#diff-72f0d44c0868e5e253d02bfc8465c474L20-L32

2020-08-23 17:09 UTC, ssnk-test commented on user_service/app/views.py
> +                    "todo:implement to env")
ичправлено 
https://github.com/ssnk-test/stage_proj/pull/10/commits/79b9c2f0d3d773ba9a417f503709db5a85f691a5

2020-08-23 17:11 UTC, ssnk-test commented on user_service/app/views.py
> +        print("LogOut valid auth")
удалены 
ссылка тут https://github.com/ssnk-test/stage_proj/pull/10/commits/eaec194810fde7f1bc9315be5c6c86ec55250157#diff-72f0d44c0868e5e253d02bfc8465c474L101-R120

2020-08-23 18:01 UTC, ssnk-test commented on user_service/alembic/env.py
> +sys.path = sys.path[:] + [".."]
нет мыслей, кроме как установить приложение как пакет
раз ок, не стал менять:)

2020-08-23 18:27 UTC, ssnk-test commented on email_service/src/email_service/asgi.py
> +# async def pp():
сделано
https://github.com/ssnk-test/stage_proj/commit/3265a824fe4eac91f3f1f52abec0fc792da0043e

2020-08-23 18:27 UTC, ssnk-test commented on mon/app_mon/asgi.py
> +#async def strt(loop):
готово
https://github.com/ssnk-test/stage_proj/commit/3265a824fe4eac91f3f1f52abec0fc792da0043e

2020-08-23 18:44 UTC, ssnk-test commented on email_service/src/email_service/views/templates.py
> +from ..models.templates import Templates
сделано
https://github.com/ssnk-test/stage_proj/commit/77889b14794366b3a0f87a729373bd26ba38ba81

2020-08-23 20:49 UTC, ssnk-test commented on email_service/src/email_service/models/__init__.py
> +    dsn="postgresql://postgres:postgres@db_email_service:5432/postgres",
готово
https://github.com/ssnk-test/stage_proj/pull/11/commits/2cd6145c9ccf8a04f8b1ec5cdc0c42a3041dcc3d

2020-08-23 21:10 UTC, ssnk-test commented on mon/cel/tasks.py
> +from ..app_mon.models.event import Event
фикс
https://github.com/ssnk-test/stage_proj/pull/11/commits/620ff6073bb5b8377ea901a95b88abe6405d1af3

2020-08-23 21:10 UTC, ssnk-test commented on mon/app_mon/views/events.py
> +from ...cel.tasks import write_event
фикс
https://github.com/ssnk-test/stage_proj/pull/11/commits/620ff6073bb5b8377ea901a95b88abe6405d1af3

2020-08-23 21:42 UTC, ssnk-test commented on mon/app_mon/models/__init__.py
> +    dsn="postgresql://postgres:postgres@db_mon_service:5432/postgres",
https://github.com/ssnk-test/stage_proj/pull/11/commits/7989f52225f17e888db2c132591212186ad423d2

2020-08-23 23:53 UTC, s3rius requested changes
Нужны доработочки.

2020-08-23 23:53 UTC, s3rius commented on email_service/src/email_service/main.py
> +    for ep in entry_points()["email_service.modules"]:
Это очень костыльно. Почему не вызывать напрямую?

2020-08-23 23:53 UTC, s3rius commented on email_service/src/email_service/main.py
> +def load_modules(app=None):
Тебе эта функция не нужна. 
Открой интерпретатор питона и напиши `import this`. Познай Дзен и живи по нему. В твоём случае нарушается один из самых главных заветов питона. `Явное лучше неявного`. Импортируй из всех модулей явно и вызывай.

2020-08-23 23:53 UTC, s3rius commented on user_service/main.py
> +    #db_pool = await init_db(app)
Коменты такие удаляй.

2020-08-24 01:04 UTC, ssnk-test commented on user_service/main.py
> +    #db_pool = await init_db(app)
Возникла какая то путаница, это пофикшено уже в https://github.com/ssnk-test/stage_proj/pull/10/commits/79b9c2f0d3d773ba9a417f503709db5a85f691a5#diff-d7c346809bfa4dcc86df129a7cd0a064L75-R25

2020-08-24 01:23 UTC, ssnk-test commented on email_service/src/email_service/main.py
> +def load_modules(app=None):
прилежная копипаста из гайда https://python-gino.org/docs/en/1.0/tutorials/fastapi.html#create-models-and-api)
убрал
https://github.com/ssnk-test/stage_proj/pull/11/commits/754762bad52b610fffb20fe69fb7b1f521de531e

2020-08-24 01:23 UTC, ssnk-test commented on email_service/src/email_service/main.py
> +    for ep in entry_points()["email_service.modules"]:
прилежная копипаста из гайда https://python-gino.org/docs/en/1.0/tutorials/fastapi.html#create-models-and-api)
убрал
https://github.com/ssnk-test/stage_proj/pull/11/commits/754762bad52b610fffb20fe69fb7b1f521de531e

2020-08-24 09:45 UTC, s3rius approved these changes
Выглядит норм.

2020-08-24 09:45 UTC, merged